language: node_js
node_js:
  - '9'
  - '8'
  - '6'

env:
  - WEBPACK_VERSION=2 EXTRACT_PLUGIN_VERSION=2
  - WEBPACK_VERSION=3 EXTRACT_PLUGIN_VERSION=3
  - WEBPACK_VERSION=4 EXTRACT_PLUGIN_VERSION=4.0.0-beta.0

install:
  - npm install
  - npm install webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$EXTRACT_PLUGIN_VERSION || true

script:
  - npm test;

after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
